### ISSUE TITLE
How to turn off blurring for ImageMaterial?

### ISSUE THREAD

**Issue by Dozer74** [helix-toolkit/helix-toolkit#581] opened 2017-11-19 08:34 UTC
Hello! 
I have RectangleVisual3D with ImageMaterial. Octocat, for excample: 

![Octocat](https://i.imgur.com/1vDHaxy.jpg)

When I increase the zoom, pixels of the image are blurred, like this:

![Blur](https://i.imgur.com/Pg9wE2x.jpg)

I need to turn off this effect. 
For simple Image class I can use `RenderOptions.BitmapScalingMode="NearestNeighbor"`:

![Clear](https://i.imgur.com/nrAk3md.jpg)

but this has no effect on RectangleVisual3D. Сan you please help me?

**Comment by tushev** [comment] 2017-12-07 19:20
I need this feature too

**Comment by holance** [comment] 2017-12-08 01:09
Please refer to this:
https://stackoverflow.com/questions/12367928/mipmapping-in-wpf

I tested and seems working fine. 

        public static Material CreateEmissiveImageMaterial(BitmapImage image, Brush diffuseBrush)
        {
            var img = new Image { Source = image };
           RenderOptions.SetCachingHint(img, CachingHint.Cache);
            RenderOptions.SetBitmapScalingMode(img, BitmapScalingMode.NearestNeighbor);
            var brush = new VisualBrush(img);
            var em = new EmissiveMaterial(brush);
            var dm = new DiffuseMaterial(diffuseBrush);
            var mg = new MaterialGroup();
            mg.Children.Add(dm);
            mg.Children.Add(em);
            return mg;
        }

**Comment by gregorsGit** [comment] 2017-12-11 07:54
Hi,
I need the same feature for the sharpDX viewer.
A label Bitmap-Image-Material is blurring much more. (When zooming around)
Only the WPF Viewer has RenderOptions for bitmap´s.

Are there any material scaling options for DirectX?
Or, what is the best way to show a Label. (No Billboard)
Need your help.

**Comment by holance** [comment] 2017-12-11 15:37
You need to create your own shader and change the sampler, which is different from WPF.

**Comment by gregorsGit** [comment] 2017-12-13 12:42
I try to port a WPF-Helix project with many VisualBrushes to WPF.SharpDX.

But I have many nogo´s.
1.) Memory-Usage to huge
2.) As told before. Blurring when zooming. Don´t know how to change the shader sampler.
3.) Black-text is gray.  (see below)
when DiffuseColor = SharpDX.Color.White;
changing
DiffuseColor = SharpDX.Color.Black.
white is not white.

![image](https://user-images.githubusercontent.com/34306200/33938860-477ab8da-e009-11e7-8171-9b2f6a137d2f.png)


So I can´t display an WPF-Text-Visual nice on a box.
Is there a better way to display such a label? 
Direct2D in 3D??
Thanks

**Comment by holance** [comment] 2017-12-13 14:55
If you did not experience performance issue with wpf version, then there's no need to convert to SharpDX version. For SharpDX version, it is not as easy to use as the wpf one, you may need some basic background on direct x to use it properly(basic rendering pipeline, shader code, etc)

For the text color, I think it's caused by other lighting colors. Try to set other colors in material to black.

**Comment by gregorsGit** [comment] 2017-12-21 10:16
For a better performance, i try to convert to SharpDX.

Changing the AmbientColor to black, its a litte bit better with the black color.
But where can i find a shader for better scaling and rendering of visuals/meshes?
Are there any shader with dynamic map sizing (examples).
-> label far away (smal size) : render only 100 pixel
-> label nearby (big size): render 10000 pixel
Thanks

**Comment by holance** [comment] 2017-12-21 19:29
I think the dynamic map you mentioned is mipmap? It is done automatically done by directx texture.

**Comment by gregorsGit** [comment] 2018-01-03 09:33
I think, I found a soloution.
Changing the shader-filter of the sampler from MIN_MAG_MIP_LINEAR to ANISOTROPIC.
Now it looks much better when i zoom around.
Hope somebody creates a new rendere with this filter-type.
Thanks.

**Comment by holance** [comment] 2018-01-03 15:38
Yes. In future 2.0, will support custom sampler in material for each texture.

**Comment by holance** [comment] 2018-02-13 01:45
Future 2.0 has been merged into develop branch. Provides custom sampler for each material texture.

**Closed by holance** 2018-02-13 01:45 UTC
Labels: help wanted, question
