### ISSUE TITLE
Windows 10 and SharpDX and DirectX12

### ISSUE THREAD

**Issue by SiNeumann** [helix-toolkit/helix-toolkit#176] opened 2015-08-05 09:10 UTC
The Setup:
I got a new Laptop with Windows 10 installed, Windows 10 comes with default installation of DirectX 12(dxdiag). My 3d tool couldn't load sharpdx_direct3d11_effects_x86.dll, which was strange since it was in the project bin folder. So I was digging around with DependencyWalker and found that it couldn't load D3DCompiler_43.dll, which may or may not be part of Directx11 and not DirectX12. 
However i stopped digging after it worked with DirectX11. 
The workaround:
 Even if Directx12 is installed, install Directx11

**Comment by Kelcyo** [comment] 2015-08-12 18:18
These guidelines do not solve the problem.
First Windows 10 does not do the downgrade, saying that already have the latest version installed (DirectX 11.1).
According to believe than DirectX problem as the Build (0.8.1.20150406T1239) when installed works perfectly in these OS. The most likely is the question of compilation.

**Comment by ikeough** [comment] 2015-09-16 12:34
I'm not 100% sure this will help, but with Dynamo, which uses Helix for 3D, we install DirectX 11 using components from the [DirectX End-User Runtimes](http://www.microsoft.com/en-us/download/details.aspx?id=8109). You can install D3DCompiler_43.dll as part of that.

**Comment by objorke** [comment] 2015-09-16 17:59
Not a bug? I am closing this... Let us know if it shoud be reopened!

**Closed by objorke** 2015-09-16 17:59 UTC
Labels: help wanted, SharpDX
