### ISSUE TITLE
White screen on all samples, Exception when creating Texture in DX11ImageSource

### ISSUE THREAD

**Issue by roy-t** [helix-toolkit/helix-toolkit#224] opened 2015-11-07 09:20 UTC
For me all samples result in a white image 

![capture](https://cloud.githubusercontent.com/assets/623634/11014496/1a0277c6-8539-11e5-8d42-28b0c1d73db6.PNG)

 After doing some digging I noticed a `SharpDx.Exception` being thrown and cought in `DX11ImageSource.cs` on line 97:

`this.renderTarget = new Texture(DX11ImageSource.device, target.Description.Width, target.Description.Height, 1, Usage.RenderTarget, format, Pool.Default, ref handle);`

	SharpDX.SharpDXException occurred
	  HResult=-2147024809
	  Message=HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

	  Source=SharpDX
	  StackTrace:
	       at SharpDX.Result.CheckError()
	       at SharpDX.Direct3D9.Device.CreateTexture(Int32 width, Int32 height, Int32 levels, Int32 usage, Format format, Pool pool, Texture textureOut, IntPtr sharedHandleRef)
	       at SharpDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool, IntPtr& sharedHandle)
	       at HelixToolkit.Wpf.SharpDX.DX11ImageSource.SetRenderTargetDX11(Texture2D target) in D:\Projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DX11ImageSource.cs:line 97
	  InnerException: 

I've inspected all the variables, here are their values:

`DX11ImageSource.device ={SharpDX.Direct3D9.DeviceEx}`
`target.Decscription.Width = 100;`
`target.Description.Height = 100;`
`format = SharpDX.Direct3D9.Format.A8R8G8B8;`
`handle = {-2147477374};`

The negative handle for the shared resources seems weird to me. But its not always negative while the exception occurs always. All the other values seem perfectly correct. I've tried the samples on another computer, and there everything works perfectly so it seems its a combination of my hardware and the code.

Specifications of the system where it doesn't work
OS: Windows 10
CPU: Intel i5 3540
RAM: 16GB (2x8)
GPU: AMD R9 280x 3GB

The system where all samples dit work is very similar. The biggest difference is that it has an Nvidia card, not an ATI card.

**Comment by roy-t** [comment] 2015-11-07 09:46
Small update, using the constructor of Texture without the last `ref handle` parameter does not throw any exceptions, but the screen is still white. So my bet is that something is wrong with the handle. Any way I can give you guys more info?

**Comment by objorke** [comment] 2015-12-02 13:42
Help wanted... I could not reproduce this issue.

**Comment by smischke** [comment] 2015-12-02 14:01
Please try one of the issues in the example browser. It has a better error reporting. 

![hxsdxexception](https://cloud.githubusercontent.com/assets/8622962/11532518/970442e8-9904-11e5-9175-8238a3a19089.png)

Have you installed the DirectX Runtime?
https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe

**Comment by smischke** [comment] 2015-12-08 11:25
Small update: It seems that the Intel Windows 10 driver causes this issue. If you have a notebook with nVidia Optimus Prime, you can switch from "Autobots" to "Integrated graphics" to force using the Intel GPU (you may need to restart Visual Studio). 

![GitHub](http://support.hp.com/doc-images/45/c03735151.jpg)

On Windows 7 systems, this is no problem. On Windows 10 systems, the aforementioned "new Texture()" call fails with "invalid params" (reason yet unknown).

**Comment by smischke** [comment] 2015-12-14 11:33
@roy-t: Could you please check if PR #228 solves your issue?
@objorke: AppVeyor test fails, but I don't think it's my fault. Something with file permissions on the build server.

**Comment by roy-t** [comment] 2015-12-14 23:44
@smischke sorry for the radio silence from my side. I think I'll have some time to check the PR tomorrow (its 0:44 here now). Will report back!

**Comment by roy-t** [comment] 2015-12-15 07:29
I'm afraid #228 doesn't solve this issue. The error message is unchanged. I understand it did solve an issue for you with 2 videocards in a laptop (so it should definitely be integrated into the main branch). But as I'm on a desktop with a dedicated R9 280X so I guess this is not the issue.

Note that since my first report I updated my videocard drivers, but this also has no effect.

**Comment by Heavywolf** [comment] 2015-12-15 20:11
Hi,
I have the same Problem on Windows 8.1. Samples for WPF all work but samples for SharpDX are all White.

**Comment by objorke** [comment] 2016-01-19 18:35
I have merged PR #228, can this issue be closed?

**Comment by roy-t** [comment] 2016-01-19 20:56
Unfortunately my graphics card broke, and with the new one (an Nvidia this time) I cannot reproduce the issue. Since I was still able to play games and other 3D apps with my old GPU I don't think the GPU breaking was related to this issue. But since I cannot reproduce it I guess we should close it. Note that (for me) it didnt have anything to do with nVidia optimus.

Thanks for the help btw, sorry I couldn't offer more insights :).

**Comment by objorke** [comment] 2016-01-20 05:07
I read your comment from Dec 15 again, and understand that the issue may not be solved, but nobody can reproduce it at the moment.
I suggest to close this issue, then re-open or create a new issue if someone can reproduce it...

**Comment by LordBenjamin** [comment] 2016-04-04 08:42
Reproduced on two identical HP workstations using an Intel HD 4600 (driving a monitor via DisplayPort) and an Nvidia NVS 315 (driving two monitors via DVI).

Can we please re-open, or should I create a new issue?

**Comment by LordBenjamin** [comment] 2016-04-04 10:56
Managed to work around by modifying the StartD3d() method in DX11ImageSource.cs:

Changed line 132 from:

`device = new DeviceEx(context, **0**, DeviceType.Hardware, IntPtr.Zero, CreateFlags.HardwareVertexProcessing | CreateFlags.Multithreaded | CreateFlags.FpuPreserve, presentparams);`

To:

`device = new DeviceEx(context, **1**, DeviceType.Hardware, IntPtr.Zero, CreateFlags.HardwareVertexProcessing | CreateFlags.Multithreaded | CreateFlags.FpuPreserve, presentparams);`

Adapter 0 was the Intel HD4600 integrated graphics, adapters 1 and 2 are the Nvidia card.

Does this help at all?

**Comment by smischke** [comment] 2016-04-04 11:44
It should also work with the Intel adapter. But as I mentioned before, if you force to use a specific adapter via nVidia Optimus, the other adapter is still enumerated but it will fail. One way to detect this is checking "Outputs".
https://github.com/helix-toolkit/helix-toolkit/pull/228/commits/9cac92c82da6e8397c0e07d535c237b5302fe86a

Could you please check what "Outputs" looks like for the selected adapter in the failing case (see: Effects.GetBestAdapter()).

**Comment by LordBenjamin** [comment] 2016-04-04 12:05
Thanks for the info - it isn't an Optimus setup, just a discreet Nvidia NVS card and the CPU integrated HD4600. As such, there is no way to force a specific adapter in the Nvidia control panel (that I can see anyway!).

I'll check the outputs and update.

**Comment by LordBenjamin** [comment] 2016-04-04 13:20
Please see below for the value of Outputs for Adapter 0:

![e29d6fc0](https://cloud.githubusercontent.com/assets/13396705/14249167/4e67ad4a-fa70-11e5-9224-d266e90f8849.PNG)

![26452cc1](https://cloud.githubusercontent.com/assets/13396705/14249171/515c083e-fa70-11e5-8b86-5bc723ef5130.PNG)

**Comment by smischke** [comment] 2016-04-04 15:07
Ok, I think I've understood the problem. DX11ImageSource always uses adapter index 0 and EffectsManager uses the "best adapter" which might be a different one. I think DX11ImageSource() should receive the adapter index used by Effects as optional parameter. I'll make a PR later.

The ShapDX version of Helix Tookit is based on some code snippets from MonoGame (see [here](https://github.com/CartBlanche/MonoGame-Samples/tree/master/WpfInteropSample)) and was improved by different people over time. So this is a remainder of the sample snippet.

**Comment by cokemal** [comment] 2016-04-05 15:14
I  got a similar issue after i upgraded to Windows 10. 

> HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Parametre hatali.

I tracked down to SharpDX class and found exception occuring at line 97 of DX11ImageSource.cs
`this.renderTarget = new Texture(DX11ImageSource.device, target.Description.Width, target.Description.Height, 1, Usage.RenderTarget, format, Pool.Default, ref handle);  `

Here is the stack trace of the exception

> "at: SharpDX.Result.CheckError()
at: SharpDX.Direct3D9.Device.CreateTexture(Int32 width, Int32 height, Int32 levels, Int32 usage, Format format, Pool pool, Texture textureOut, IntPtr sharedHandleRef)
at: SharpDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool, IntPtr& sharedHandle) 
at: HelixToolkit.Wpf.SharpDX.DX11ImageSource.SetRenderTargetDX11(Texture2D target) HelixToolkit.Wpf.SharpDX\\Controls\\DX11ImageSource.cs: line 97"

**Comment by smischke** [comment] 2016-04-06 08:12
Could you all please test if #270 solves this issue?

**Comment by LordBenjamin** [comment] 2016-04-06 10:38
Works for me, thanks!

**Closed** 2016-04-15 07:50 UTC
Labels: help wanted, please verify, SharpDX, unconfirmed bug
