### ISSUE TITLE
PointGeometryModel3D - HitTestThickness property has no effect? (SharpDX WPF on .net core)

### ISSUE THREAD

**Issue by chrkon** [helix-toolkit/helix-toolkit#1416] opened 2020-10-05 08:22 UTC
I have some PointGeometryModel3D instances as childs in a GroupModel3D instance. Now I want to select points by mouse clicks.
So I have added the **Mouse3DDown** Eventhandler to the GroupModel3D instance.
Then I have set the **Size** and the **HitTestThickness** to the PointGeometryModel3D instances, because a single point is normally to small to hit directly by mouse.

But even if I set the Size to 10,10 and the HitTestThickness to 50, the **Mouse3DDown** event only occurs if I hit the point directly. It seems, that the HitTestThickness is not working correctly.

I have added this code into the **HelixToolkit.SharpDX.Core.sln** / **CoreWpfTest** project to test and show the behaviour:

_MainWindow.xaml_
``` 
           <hx:GroupModel3D  
                Mouse3DDown="Model3D_OnMouse3DDown">
                <hx:PointGeometryModel3D 
                    x:Name="PointModel3D"
                    Geometry="{Binding PointGeometry}"
                    Size="10,10"
                    HitTestThickness="50"
                    Color="Blue" />
                <hx:PointGeometryModel3D 
                    x:Name="PointModel3DV2"
                    Geometry="{Binding PointGeometry2}"
                    Size="10,10"
                    HitTestThickness="50"
                    Color="Violet" />
            </hx:GroupModel3D>
```
_MainWindow.xaml.cs:_
``` 
      private void Model3D_OnMouse3DDown(object? sender, MouseDown3DEventArgs e)
        {
            Debug.Write((e.OriginalSource as PointGeometryModel3D)?.Name);
            Debug.Write(": ");
            Debug.WriteLine(e.HitTestResult);
        }
```
_MainViewModel.cs_
```
      public Geometry3D PointGeometry { get; } = new PointGeometry3D
        {
            Positions = new Vector3Collection
            {
                new Vector3(10f, 10f, 0f),
                new Vector3(30f,10f,0f)
            }
        };
        public Geometry3D PointGeometry2 { get; } = new PointGeometry3D
        {
            Positions = new Vector3Collection
            {
                new Vector3(10f, 10f, 30f),
                new Vector3(30f,10f,30f)
            }
        };
```

**Comment by holance** [comment] 2020-10-07 23:20
This issue is caused by small bounding box on point collection. The bounding box has no way to know the point size rendered on screen. 
Will add an option to turn off bounding box check during hit test.

**Comment by holance** [comment] 2021-04-14 17:12
Should have been fixed in https://github.com/helix-toolkit/helix-toolkit/pull/1562

**Closed by holance** 2021-04-14 17:12 UTC
Labels: SharpDX, bug
