### ISSUE TITLE
Viewcube not clickable after modelupdirection change while running

### ISSUE THREAD

**Issue by jotschgl** [helix-toolkit/helix-toolkit#586] opened 2017-12-12 08:02 UTC
Only the "shadow" circle reacts on mouse enter and mouse leave. The cube is following the rotation of the view, but not reacting on clicks.

I've added a file to reproduce it. Just replace the MainWindow Files of the simple demo and click the new menu item.

[SimpleDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/1550698/SimpleDemo.zip)

**Comment by holance** [comment] 2017-12-20 00:27
Proper fix has been committed. Root cause is the model change in VisualCollection3D did not observed the mouse click. Not sure whether it is a bug from Microsoft or not.

Fix has been committed at https://github.com/helix-toolkit/helix-toolkit/tree/ab8b54b47b50c7209544a01553529aae577375d5
Comment build error has been fixed at https://github.com/helix-toolkit/helix-toolkit/tree/f1d1c58adc25747850bef5a2cb9b5fe682d4cbb1

Supposed to use pull request to fix, sorry about that.

**Closed by holance** 2017-12-20 00:27 UTC
Labels: bug, you take it
