### ISSUE TITLE
swapchain rendering bugs (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1053] opened 2019-01-02 07:07 UTC
Hi,
I try to use the swapchain rendering.
But I get some bugs.
1.) colors of transprent objects are dark/black when I use EnableOITRendering=true. (default)
(EnableOITRendering=false)
![grafik](https://user-images.githubusercontent.com/34306200/50582212-f6b1af80-0e60-11e9-8269-3128e95dc659.png)
(EnableOITRendering=true)
![grafik](https://user-images.githubusercontent.com/34306200/50582231-2791e480-0e61-11e9-8488-d8c48557393f.png)
2.) Touch feature: Pan and other not working.
-> Pan is not working. (zoom with two finger is slow, but working)??
3.) Got one exception. (Can´t reproduce it now.)
Thanks

**Comment by gregorsGit** [comment] 2019-01-02 08:02
I try the latest dev-source-version and point 1. is fixed.

**Comment by gregorsGit** [comment] 2019-01-02 09:35
ok. 
I hope .NET Core 3.X will make wpf faster and using less memory.

I get the following expecption only with swapchain and shared model .
![grafik](https://user-images.githubusercontent.com/34306200/50586369-7186c480-0e79-11e9-987c-2224dd0f8bb7.png)
Disable swapchain solve this issue.
But you can close this issue when this call-stack don´t help.

**Comment by holance** [comment] 2019-04-02 15:02
Seems like it is related to D2D, duplicate of the issue #1125. Close for now.

**Closed by holance** 2019-04-02 15:02 UTC
Labels: SharpDX, enhancement
