### ISSUE TITLE
Zoom to mouse location with wheel

### ISSUE THREAD

**Issue by Sakroe** [helix-toolkit/helix-toolkit#289] opened 2016-06-23 12:25 UTC
Currently zooming with the mouse wheel to the center.
I want to change it to be zoomed to the mouse pointer.
I have so tried to solve:

`
private void Helix3D_PreviewMouseWheel(object sender, MouseWheelEventArgs e)
{
  var vp = sender as HelixViewport3D;
  Helix3D.CameraController.CameraPosition = vp.CursorPosition.Value;
}
`
This works, but not really good.
Does anyone know a better solution?

**Comment by chrkon** [comment] 2016-06-24 07:05
Hello Sakroe,
I think you can use the **ZoomAroundMouseDownPoint** property. Set it to **True** and Helix will zoom to the mouse position.

**Comment by chrkon** [comment] 2016-06-24 07:16
Hello everybody,
I have checked Sakroe's question with the Surface Sample. I have added the **ZoomAroundMouseDownPoint=True** property and I saw that the Zoom to Mouse Point function is working fine if I use the wheel of the mouse. 
But then I saw the issue Sakroe has mentioned. So I think he has found a small bug.

If the mouse is over a 3D Model it works. 
But if the mouse cursor is not over a 3D model the zoom method is using the center of the view and not the Cursor position. I think we should take a look at this.

Kind regards
Christof

**Comment by smischke** [comment] 2016-06-24 07:46
The problem is, if the mouse is not over geometry, you don't have a center / origin to zoom to. If you are looking towards the xy plane, the z / depth is missing for example. One could intersect with the world origin in these cases, but I'm not sure if the result is always what one would expect.

**Comment by Sakroe** [comment] 2016-06-24 08:29
I tested with the example CursorPositionDemo. If the ZoomAroundMouseDownPoint property is true and the mouse is over the model, it works. But without a model, it does not working. Then zooms centers.
My problem is, in my project, there are only very small models (pixels).

**Comment by chrkon** [comment] 2016-06-24 09:17
I have taken a look into the source code. In **line 2267** of file **CameraControler.cs** the nearest point is calculated from the 2D cursor information. If this calculation fails, the Zoom Method use the center of the View.
Perhaps we can use the 3D cursor position directly? I will try it.

**Comment by chrkon** [comment] 2016-09-10 18:21
I think this issue is already solved by commiting #290. 
Kind regards,
Christof

**Comment by mk48** [comment] 2016-12-15 08:13
If this is solved, could you please close it?

**Closed** 2016-12-15 08:32 UTC
Labels: help wanted, unconfirmed bug, you take it
