### ISSUE TITLE
new error with ExtrudedVisual3D

### ISSUE THREAD

**Issue by MichaelEwe** [helix-toolkit/helix-toolkit#179] opened 2015-08-05 13:22 UTC
Incorporating the change from @lcouz into master renders ExtrudedVisual3D unusable.

From the commit comment I see, the intentions were ok: extrusion needs at least two points in the path.
Unfortunately it is coded the other way round. In my opinion the change should read:

    if (this.Path == null || this.Path.Count < 2)
    {
        return null;
    }

and not

    if (this.Path == null || this.Path.Count >= 2)
    {
        return null;
    }

How to reproduce: just open the "Mesh Visuals" example in example browser and see the crash when referencing the non existing array elements.

**Comment by objorke** [comment] 2015-08-05 13:36
Duplicate of #175?
Fixed by #177

**Closed by objorke** 2015-08-05 13:36 UTC
