### ISSUE TITLE
Wavefront Object Reader does not read normal maps

### ISSUE THREAD

**Issue by tekken57** [helix-toolkit/helix-toolkit#1104] opened 2019-02-20 10:51 UTC
Good afternoon. 

The Helix toolkit doesn't seem to read normal maps when opening wavefront objects with an associated MTL file. I am defining my material as follows:

newmtl Material 1
Ns 10.000000
Ni 1.500000
Tr 0.000000
Tf 1.000000 1.000000 1.000000
Ke 0.000000 0.000000 0.000000
Ka 0.588000 0.588000 0.588000
Kd 0.588000 0.588000 0.588000
Ks 0.000000 0.000000 0.000000
d 1.000000
Ns  0.0
illum 2
map_Kd head.dds
bump head_n.dds

I've also tried the map_bump prefix but it still does not load. 

Secondly are there any plans for adding support for the proposed pbr material naming convention in the mtl files as detailed on the mtl format wikipedia page?

**Comment by holance** [comment] 2019-02-20 18:13
Could you share the model with issue?

For PBR naming convension, since we are moving to use Assimp importer, as long as Assimp adopt the standard, it will be supported.

**Comment by tekken57** [comment] 2019-02-21 06:30
Good morning. 

Thank you for responding. I am attaching a sample model with textures below
[model_sample.zip](https://github.com/helix-toolkit/helix-toolkit/files/2887941/model_sample.zip)

**Comment by holance** [comment] 2019-02-21 06:58
From my test, it is loading normal map correctly. Are you running WPF or SharpDX.WPF version?

**Comment by tekken57** [comment] 2019-02-21 11:08
I am running the WPF version.

**Comment by tekken57** [comment] 2019-02-21 11:31
To illustrate, here's a picture of what the model looks like when I list the normal map in the mtl file and what it looks like when the normal map is not listed. 

I'm also attaching pictures of what the normal map looks like in mudbox when applied to the model:

![helix_normals](https://user-images.githubusercontent.com/45447397/53166037-e5715d80-35dc-11e9-876c-0a41169b7296.jpg)

**Comment by holance** [comment] 2019-02-21 18:08
Ok, the problem is HelixToolkit.WPF does not support Normal Map. Because WPF itself does not support normal map.

Only WPF.SharpDX supports normal map.

**Closed** 2019-02-27 17:56 UTC
Labels: WPF, question
