### ISSUE TITLE
Viewport renderScreenshot not working correct

### ISSUE THREAD

**Issue by Terminatorder1** [helix-toolkit/helix-toolkit#1401] opened 2020-09-19 22:26 UTC
I have following Issue,

I want to render my Viewport into a bitmap. But the result of it is not as it should be. 

Im rendering the bitmap with 2 diffrent ways:
```
- MainWindow.imgboxx.Source = h_viewport.Viewport.RenderBitmap(new SolidColorBrush(Colors.White));
- MainWindow.imgboxx.Source = Viewport3DHelper.RenderBitmap(h_viewport.Viewport,(new SolidColorBrush(Colors.White)));
```

![image](https://user-images.githubusercontent.com/3902938/93690375-d794fe80-fad7-11ea-96a1-e15ce4862cf4.png)
Left: the viewport  ; Right: the rendered Bitmap

What im doing wrong ?

*** The 3DModels are imported via STL.File from a CAD Software.

**Comment by chrkon** [comment] 2020-10-17 22:54
Hello @Terminatorder1, hello @holance,
I have tried to reproduce this failure.

For this I have added a "render bitmap to clipboard" command into the WPF Example project "ModelViewer". Now it was easy to load different models and convert them into bitmaps by pressing `CTRL-C`. The images were pasted into the image viewer application '[irfanView](https://www.irfanview.com/)'.

This code renders the bitmap and stores it into the clipboard:
```
 var bitmap = Viewport3DHelper.RenderBitmap(this.viewport.Viewport, new SolidColorBrush(Colors.White));
 try
 {
    Clipboard.Clear();
    Clipboard.SetImage(bitmap);
    this.ApplicationTitle = string.Format(TitleFormatString, this.CurrentModelPath,"(rendered as bitmap into clipboard)");
 }
 catch (Exception)
 {
     this.ApplicationTitle = string.Format(TitleFormatString, this.CurrentModelPath, "(storing in clipboard failed)");
  }
```

**I have made tests with different model files, but I was not able to reproduce a wrong behaviour like above.** 

@Terminatorder1 can you post the STL file with your model?  Or can you use the changed Model viewer to check it?

The sources for the modified Model viewer are in my helix-toolkit fork on github. (Branch "issue/#1401RenderBitmapFailure")
This is the [Link to my helix-toolkit fork branch 'issue/#1401RenderBitmapFailure'](https://github.com/chrkon/helix-toolkit/tree/issue/%231401RenderBitmapFailure)

Kind regards,
Christof

**Comment by chrkon** [comment] 2020-11-02 22:12
Hi @holance, 
I think we should close this issue. I was not able to reproduce the issue and I have not received any answer in the last 16 days.

Kind regards,
Christof

**Closed** 2020-11-03 00:29 UTC
Labels: WPF, bug, help wanted
